gene_default: &gene_default
  tree:
    method_cl: "--method iqtree --substitution-model HKY+F+I+R2 --tree-builder-args='-safe'"
  refine:
    clock_rate_cl: "--clock-rate 3.02e-7 --clock-std-dev 8.55e-8"
genes:
  Tp0326:
    <<: *gene_default
  Tp0865:
    <<: *gene_default
describe:
  gene:
    postscript: |
      - The <code>Nucleotide diversity of the genome</code> panel provides insights into the variability of biologically relevant gene regions.
      These were either predicted using [DeepTMHMM](https://dtu.biolib.com/DeepTMHMM/) or curated manually.
      Clicking on a track will zoom into this region; by clicking on the individual bars, coloring is performed according to amino acid variants instead of nucleotide variants.
      - <code>Extracellular loop</code> (ECL) amino acid sequences and the <code>Extracellular loop type</code> — the combination of translated ECL sequences — are integrated as metadata.
      To ensure robust representation, only ECL types present in at least 1% of all source samples are displayed. ECLs enumerated as 0 correspond to the reference sequence.
      - Samples that reflect the reference sequence and are not the representative sample of the reference genome are excluded from this dataset.
      - TrepoGen gene datasets provide the view of a single gene only and do not represent a comprehensive genomic context!
    Tp0326: |
      #### Tp0326

      BamA (TP0326) is the central component of the molecular machinery that inserts newly exported OMPs into the spirochete’s outer membrane.
      BamA in _T. pallidum_ is bipartite and consists of a predicted 16-stranded β-barrel with eight extracellular loops (ECLs) and five polypeptide transport-associated (POTRA) domains within the periplasm.

      Additional information on Tp0326 (BamA) can be found in the following references:
      - [UniProt O83346](https://www.uniprot.org/uniprotkb/O83346/entry)
    Tp0865: |
      #### Tp0865

      TP0865, one of five FadL orthologs in _T. pallidum_, contains structural features found in canonical fatty acid transporters: a 14-stranded β-barrel with seven ECLs and an N-terminal hatch domain that plugs the lumen of the barrel.

      Additional information on Tp0865 can be found in the following references:
      - [UniProt O83837](https://www.uniprot.org/uniprotkb/O83837/entry)
