genome_default: &genome_default
  tree:
    method_cl: "--method iqtree --substitution-model HKY+F+ASC+R2 --tree-builder-args='-safe -pathogen'"
  refine:
    clock_rate_cl: "--clock-rate 3.02e-7 --clock-std-dev 8.55e-8"
genomes:
  TPASS-308:
    <<: *genome_default
  TPASS-2588:
    <<: *genome_default
describe:
  genome:
    TPASS-308: |
      #### Genome

      This genome dataset is constructed from whole-genome variants, featuring the complete phylogenetic context of _T. pallidum_.
      Prior to phylogenetic inference, curated recombinant regions were masked to avoid spurious tree building.
      - The <code>Nucleotide diversity of genome</code> panel features all unmasked positions and individual genes that are also available as gene datasets are highlighted.
      - Sublineage and BAP assignments are available via the metadata. Currently schemas introduced by [Beale _et al._ 2021](https://doi.org/10.1038/s41564-021-01000-z), [Taouk _et al._ 2022](https://doi.org/10.1016/s2666-5247(22)00035-0), and [Sena _et al._ 2024](https://doi.org/10.1016/S2666-5247(24)00087-9) are supported.
      - Known macrolide resistance mutations, mediated by 23S rRNA mutations 2058A→G (positions 283,691 and 235,246 in the used reference genome) and 2059A→G (positions 283,692 and 235,247 in the used reference genome), are available via the metadata.
    TPASS-2588: |
      #### Genome

      This genome dataset is constructed from whole-genome variants, featuring the complete phylogenetic context of _T. pallidum_.
      Prior to phylogenetic inference, curated recombinant regions were masked to avoid spurious tree building.
      - The <code>Nucleotide diversity of genome</code> panel features all unmasked positions and individual genes that are also available as gene datasets are highlighted.
      - Sublineage and BAP assignments are available via the metadata. Currently schemas introduced by [Beale _et al._ 2021](https://doi.org/10.1038/s41564-021-01000-z), [Taouk _et al._ 2022](https://doi.org/10.1016/s2666-5247(22)00035-0), and [Sena _et al._ 2024](https://doi.org/10.1016/S2666-5247(24)00087-9) are supported.
      - Known macrolide resistance mutations, mediated by 23S rRNA mutations 2058A→G (positions 283,691 and 235,246 in the used reference genome) and 2059A→G (positions 283,692 and 235,247 in the used reference genome), are available via the metadata.
