sources:

  TPA-SS14:
    reference_sample: "CP004011"
    meta_identifier: "sra"

    # Parameters to build the initial tree from this data source.
    tree:
      # The auto substitution model selection may be disabled in the future for runtime increase. HKY+F+ASC+R2 performed good for the 2588 source.
      method_cl: "--method iqtree --substitution-model auto --tree-builder-args='-safe' --nthreads 12"

    # Optional command line arguments for tree refinement.
    refine:
      year_bounds_cl: "--year-bounds 2025 2000"
      precision: 3
      iterations: 3
      # The fixed clock rate is based on literature references: https://pmc.ncbi.nlm.nih.gov/articles/PMC8612932/.
      #clock_rate_cl: "--clock-rate 1.28e-7 --clock-std-dev 1.67e-8"
      clock_rate_cl: ""

    # Metadata fields to infer for ancestral states (internal nodes of the tree).
    traits:
      columns: "subspecies country region date"

    # Additional metadata columns to be included in the Auspice export. These will not be available for coloring.
    export:
      metadata_columns: "Label BioSample BioProject PMID Center Host Origin"

    # Data source and metadata description.
    describe: |
      ##### Dataset

      The <code>TPA-SS14</code> dataset currently comprises whole-genome variants of 2,487 individual _Treponema pallidum_ ssp. _pallidum_, _pertenue_, and _endemicum_ samples, genotyped against the SS14 reference genome [NC_021508.1](https://www.ncbi.nlm.nih.gov/nuccore/NC_021508.1/).
      Variants include **single nucleotide variants (SNVs) and InDels**, providing insight into the full spectrum of sequence changes and featuring the complete phylogenetic context of _T. pallidum_.

      **Note:** Given that the reported genotyping is based on an SS14 reference genome, reported variants may be reference-biased. Consequently, indel calls, particularly in homopolymeric regions, should be interpreted with caution. This extends to gene sequences inferred from the reported variants.

      ##### Metadata

      Accompanying **metadata includes** the sampling <code>Date</code>, <code>Country</code>, and <code>Region</code>, as well as <code>Subspecies</code> designations, including division into the Nichols and SS14 lineages.
      Moreover, the **sublineage and Bayesian analysis of population structure (BAP) assignments** introduced by [Beale _et al._ 2021](https://doi.org/10.1038/s41564-021-01000-z), [Taouk _et al._ 2022](https://doi.org/10.1016/s2666-5247(22)00035-0), and [Sena _et al._ 2024](https://doi.org/10.1016/S2666-5247(24)00087-9) are available.
      
      To communicate **data quality**, we provide the <code>Effective Coverage</code> as the mean coverage multiplied by the breadth of coverage (≥5X) per sample.
      Available whole genome sequencing samples with a breadth of coverage below 75% at 5X were excluded from the dataset.

      To raise awareness of **antimicrobial resistance (AMR)**, we annotate known resistance-associated variants:
      - **Macrolide resistance** mediated by 23S rRNA mutations A2058G (positions 283,691 and 235,246 in the used reference genome) and A2059G (positions 283,692 and 235,247 in the used reference genome) [PMC 3592075](https://pmc.ncbi.nlm.nih.gov/articles/PMC3592075/).
      - Putative **ceftriaxone and penicillin G resistance** associated with TP0705 variants of interest (VOIs) A1873G (position 773,095 in the used reference genome) and G2122A (position 772,846 in the used reference genome) [PMC 12152143](https://pmc.ncbi.nlm.nih.gov/articles/PMC12152143/).

    # Specification of genes to use for this data source.
    genes:
      TP0136:
        describe: |
          TP0136 is a surface-exposed lipoprotein of _T. pallidum_ that plays a critical role in adhesion and pathogenesis.
          It facilitates the binding of bacteria to host endothelial cells and the extracellular matrix.
          TP0136 has been the focus of extensive research as a potential primary syphilis vaccine candidate, given its surface exposure [DOI s41541-025-01330-7](https://www.nature.com/articles/s41541-025-01330-7).
          TP0136 is employed to characterize and differentiate _T. pallidum_ subspecies, particularly subsp. _pertenue_, the agent of yaws [PMC 6197692](https://pmc.ncbi.nlm.nih.gov/articles/PMC6197692/).

          Additional information on TP0136 can be found at:
          - [UniProt O83172](https://www.uniprot.org/uniprotkb/O83172/entry)
      TP0326:
        describe: |
          TP0326 (BamA) is the central component of the molecular machinery that inserts OMPs into the spirochete's outer membrane.
          TP0326 is bipartite and consists of a predicted 16-stranded β-barrel with eight extracellular loops (ECLs) and five polypeptide transport-associated (POTRA) domains within the periplasm.
          It has been demonstrated that pools of human syphilitic sera from the USA and Colombia exhibited the capacity to recognize both the N-terminal POTRA-containing and C-terminal beta-barrel domains, as well as ECL4.
          This finding suggests that TP0326 stimulates the human immune system and might constitute a potential vaccine target [PMC 4420902](https://pmc.ncbi.nlm.nih.gov/articles/PMC4420902/).

          Additional information on TP0326 can be found at:
          - [UniProt O83346](https://www.uniprot.org/uniprotkb/O83346/entry)
      TP0435:
        describe: |
          TP0435 (also Tp17/Tpp17) is a highly abundant lipoprotein found in _T. pallidum_ that is partially exposed on the surface of the bacterium.
          While the precise function of this protein is not yet fully elucidated, research findings indicate its role as a cytadhesin, facilitating the binding of the bacterium to mammalian cells.
          TP0435 has been identified as an immunodominant antigen [DOI srep25593](https://www.nature.com/articles/srep25593).

          Additional information on TP0435 can be found at:
          - [UniProt P29722](https://www.uniprot.org/uniprotkb/P29722/entry)
      TP0548:
        describe: |
          TP0548 belongs to the FadL family, which facilitates the transport of long-chain fatty acids across the outer membrane, thereby providing essential nutrients for the bacterium.
          Its encoding gene is of particular importance in the context of various typing approaches [PMID 33093286](https://pubmed.ncbi.nlm.nih.gov/33093286/).

          Additional information on TP0548 can be found at:
          - [UniProt O83559](https://www.uniprot.org/uniprotkb/O83559/entry)
      TP0574:
        describe: |
          TP0574 (also Tp47/Tpp47) is a penicillin-binding outer membrane lipoprotein.
          It has been demonstrated that TP0574-induced PGE2 production contributes to the inhibition of macrophage phagocytosis, which potentially facilitates immune evasion during infection [PMID 38258964](https://pubmed.ncbi.nlm.nih.gov/38258964/).

          Additional information on TP0574 can be found at:
          - [UniProt P29723](https://www.uniprot.org/uniprotkb/P29723/entry)
      TP0705:
        describe: |
          TP0705 is a periplasmic penicillin-binding protein, which is essential for the synthesis and cross-linking of the bacterial cell wall.
          Recent studies have identified specific genetic variations, notably the A1873G mutation, that are associated with reduced susceptibility to penicillin G and ceftriaxone in _T. pallidum_ [PMC 12152143](https://pmc.ncbi.nlm.nih.gov/articles/PMC12152143/).

          Additional information on TP0705 can be found at:
          - [UniProt O83703 ](https://www.uniprot.org/uniprot/O83703/entry)
      TP0751:
        describe: |
          Pallilysin, a multifunctional metalloprotease and vascular adhesin, facilitates the dissemination of _T. pallidum_ throughout its host by employing its lipocalin domain to firmly attach the bacteria to host cells and components of the extracellular matrix [DOI s41598-017-01589-4](https://www.nature.com/articles/s41598-017-01589-4).

          Additional information on TP0751 can be found at:
          - [UniProt O83732](https://www.uniprot.org/uniprotkb/O83732/entry)
      TP0856:
        describe: |
          TP0856 belongs to the FadL family, which facilitates the transport of long-chain fatty acids across the outer membrane, thereby providing essential nutrients for the bacterium. Studies have identified ECL2 and ECL4 as being highly immunogenic and surface-exposed, thus rendering them excellent candidates for a multivalent syphilis vaccine [PMC 9426418](https://pmc.ncbi.nlm.nih.gov/articles/PMC9426418/).

          Additional information on TP0856 can be found at:
          - [UniProt O83828](https://www.uniprot.org/uniprotkb/O83828/entry)
      TP0858:
        describe: |
          TP0858 belongs to the FadL family, which facilitates the transport of long-chain fatty acids across the outer membrane, thereby providing essential nutrients for the bacterium. Studies have identified ECL2 and ECL4 as being highly immunogenic and surface-exposed, thus rendering them excellent candidates for a multivalent syphilis vaccine [PMC 9426418](https://pmc.ncbi.nlm.nih.gov/articles/PMC9426418/).
          TP0858 is employed to characterize and differentiate _T. pallidum_ subspecies, particularly subsp. _pertenue_, the agent of yaws [PMC 6197692](https://pmc.ncbi.nlm.nih.gov/articles/PMC6197692/).

          Additional information on TP0858 can be found in the following references:
          - [UniProt O83830](https://www.uniprot.org/uniprotkb/O83830/entry)  
      TP0859:
        describe: |
          TP0859 belongs to the FadL family, which facilitates the transport of long-chain fatty acids across the outer membrane, thereby providing essential nutrients for the bacterium.
          TP0859 shows variant proteoforms and recombination in clinical strains, but is still being investigated as a potential vaccine candidate due to its surface exposure [PMC 8407342](https://pmc.ncbi.nlm.nih.gov/articles/PMC8407342/).

          Additional information on TP0859 can be found in the following references:
          - [UniProt O83839](https://www.uniprot.org/uniprotkb/O83839/entry)
      TP0865:
        describe: |
          TP0865 belongs to the FadL family, which facilitates the transport of long-chain fatty acids across the outer membrane, thereby providing essential nutrients for the bacterium.
          TP0865 shows variant proteoforms and recombination in clinical strains, but is still being investigated as a potential vaccine candidate due to its surface exposure [PMC 8407342](https://pmc.ncbi.nlm.nih.gov/articles/PMC8407342/).

          Additional information on TP0865 can be found in the following references:
          - [UniProt O83837](https://www.uniprot.org/uniprotkb/O83837/entry)
